
# Publish package on release branch if it's tagged with 'v*'
name: release & publish workflow

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the default branch
  push:
    branches:
      - main
    tags:
      - 'v*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-release-draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# todo: Enable below to auto-publish these packages to PyPI on new push with tags
  # This workflow contains a single job called "build"
  release:
    name: Build and release
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: 3.10
          cache: pip
          cache-dependency-path: 'pyproject.toml'

      - name: Install dependencies
        run: pip install -e '.[dev]'

#      - name: publish documentation
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          personal_token: ${{ secrets.PERSONAL_TOKEN }}
#          publish_dir: ./site

      - name: Build wheels and source tarball
        run: python -m build .

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip_existing: true
